\doxysection{node\+\_\+modules/node-\/domexception Directory Reference}
\hypertarget{dir_49b4d0479cc0bfd57fd824a28640f72b}{}\label{dir_49b4d0479cc0bfd57fd824a28640f72b}\index{node\_modules/node-\/domexception Directory Reference@{node\_modules/node-\/domexception Directory Reference}}


\doxysubsection{Detailed Description}
An implementation of the DOMException class from Node\+JS

Node\+JS has DOMException built in, but it\textquotesingle{}s not globally available, and you can\textquotesingle{}t require/import it from somewhere.

This package exposes the \href{https://developer.mozilla.org/en-US/docs/Web/API/DOMException}{\texttt{ {\ttfamily DOMException}}} class that comes from Node\+JS itself. (including all of the legacy codes)

\textsubscript{(plz don\textquotesingle{}t depend on this package in any other environment other than node \texorpdfstring{$>$}{>}=10.\+5)}


\begin{DoxyCode}{0}
\DoxyCodeLine{import\ DOMException\ from\ 'node-\/domexception'}
\DoxyCodeLine{import\ \{\ MessageChannel\ \}\ from\ 'worker\_threads'}
\DoxyCodeLine{}
\DoxyCodeLine{async\ function\ hello()\ \{}
\DoxyCodeLine{\ \ const\ port\ =\ new\ MessageChannel().port1}
\DoxyCodeLine{\ \ const\ ab\ =\ new\ ArrayBuffer()}
\DoxyCodeLine{\ \ port.postMessage(ab,\ [ab,\ ab])}
\DoxyCodeLine{\}}
\DoxyCodeLine{}
\DoxyCodeLine{hello().catch(err\ =>\ \{}
\DoxyCodeLine{\ \ console.assert(err.name\ ===\ 'DataCloneError')}
\DoxyCodeLine{\ \ console.assert(err.code\ ===\ 25)}
\DoxyCodeLine{\ \ console.assert(err\ instanceof\ DOMException)}
\DoxyCodeLine{\})}
\DoxyCodeLine{}
\DoxyCodeLine{const\ e1\ =\ new\ DOMException('Something\ went\ wrong',\ 'BadThingsError')}
\DoxyCodeLine{console.assert(e1.name\ ===\ 'BadThingsError')}
\DoxyCodeLine{console.assert(e1.code\ ===\ 0)}
\DoxyCodeLine{}
\DoxyCodeLine{const\ e2\ =\ new\ DOMException('Another\ exciting\ error\ message',\ 'NoModificationAllowedError')}
\DoxyCodeLine{console.assert(e2.name\ ===\ 'NoModificationAllowedError')}
\DoxyCodeLine{console.assert(e2.code\ ===\ 7)}
\DoxyCodeLine{}
\DoxyCodeLine{console.assert(DOMException.INUSE\_ATTRIBUTE\_ERR\ ===\ 10)}

\end{DoxyCode}
\hypertarget{README.md_autotoc_md24572}{}\doxysubsection{\texorpdfstring{Background}{Background}}\label{README.md_autotoc_md24572}
The only possible way is to use some web-\/ish tools that have been introduced into Node\+JS that throws a DOMException and catch the constructor. This is exactly what this package dose for you and exposes it.~\newline
 This way you will have the same class that Node\+JS has and you can check if the error is a instance of DOMException.~\newline
 The instanceof check would not have worked with a custom class such as the DOMException provided by domenic which also is much larger in size since it has to re-\/construct the hole class from the ground up.

The DOMException is used in many places such as the Fetch API, File \& Blobs, Post\+Messaging and more. ~\newline
 Why they decided to call it {\bfseries{DOM}}, I don\textquotesingle{}t know

Please consider sponsoring if you find this helpful 